#!/export/home/liuhui/opt/bin/python3

""" This script used to check the data that may be optimization
    or EDA is correct 
"""
import re
import glob
import os
import sys
import common

def checkOne ( fName ):
    """
        CheckOne    Check one file
    """
    # use to check "******" string which contain in 
    # incorrect EDA output file
    reg = re.compile('(\*){5,}')   
    #print( fName )
    try:  
        lcd  = open( fName, 'r' )
    except IOError:
        print( "Open file '" + fName + "' error!" )
        print( "Please chech the file exist." )
        sys.exit(1)

    lcd_data = lcd.readlines()
    datablocks = common.SplitToBlock(lcd_data)
    
    if fName.find('eda') != -1:    
        i = 22
        suffix = 'lcd'
    elif fName.find('opt') != -1:
        i = 0
        suffix = 'cor'

    if len( datablocks ) < i:
        print("\nThe data in '" + fName + "' is not complete. \
        Please Check the '" + suffix + "' file\n")
        sys.exit(1)

    if (len(lcd_data) < 2):
    #the file has not any data, if the length of lcd_data is 1
        print( "\n---File '" + fName + "' is empty !---" )
        print( "---May be Gamess computed error,\n \
    Please check output file---\n" )
        sys.exit(1)
    elif( len( reg.findall( ''.join(lcd_data) ) ) > 11 ):
    # check output data is correct by find the string "****"
        print( "\n---'"+ fName +"' computed sucessfully！\n \
    but the file contain'*****', You need modify manually---\n" )
        lcd.close()
        sys.exit(1)
    else:
        print( "---File '" + fName + "' is normal!---" )
        sys.exit(0)

def checkdata( file_type ):
    """
    checkdata       the function used to check the output data is 
                    correct and complete.
        file_type   the file type need to check. 
                    if you want to check some type file in current,
                    just enter the suffix of the file; and if check
                    one file, just enter the file name.
                    Notice:
                        Now, the script just can check "lcd" and "cor"
                    file, the output is error if check other file.

                    "lcd" is EDA output file and contain the LCD DIPLE data.
                    "cor" is optimized data and contain the optimized 
                    coordiantion
    """
    if len(file_type) > 3:
        checkOne( file_type )
    elif file_type == None:
        print( "Please Type in the file name which you want to check" )
        sys.exit(1)
    else:
        # get current dir which the command run
        cur_dir = os.getcwd()   
        
        for lcd_file in glob.glob( cur_dir + '/*.' + file_type ):
            # find the file whick you want to check in current dir
            filename = lcd_file.split('/')[-1]
            checkOne( filename )

    print( "Check completely!" )
    return 1    #normal exit

if __name__ == "__main__":
    if (len(sys.argv) == 1):
        print( "---Please type in the file type which you want!---" )
    else:
# test:      print(sys.argv)
        checkdata( sys.argv[1] )
