#!/bin/bash

#********************************************************
# this code used to get LMOEDA compute data 
# LCD DIPOLES
# ........
# ........
# ...DONE WITH ENERGY LOCALIZATION...
# and output the data to filename.lcd
#********************************************************
#echo $1
i=$1
i_end=$(( 5 + i ))
echo $i_end

if [ -z $2 ];then
#判断是否有输入路径,如果没有输入，则查找当前路径
    filepath=.
else
    filepath=$2
fi

#查找当前路径下的eda计算文件
for filename in $filepath/*opt*.out
do
    sedone $filename
    echo "Have already finished ananlyzing a file, please check the data from the ${filename%.*}.cor file."
done

echo "Have already finished analyzing all data in this dirctionary, please check the cor file"

echo "Now, start to check the data! Please wait a minute."
checkdata cor
