#!/bin/bash

#********************************************************
# this code used to get LMOEDA compute data 
# LCD DIPOLES
# ........
# ........
# ...DONE WITH ENERGY LOCALIZATION...
# and output the data to filename.lcd
#********************************************************
echo $1
if [ -z $1 ];then
    filepath=.
else
    filepath=$1
fi

#echo $0
#查找当前路径下的eda计算文件
for filename in $filepath/*eda*.out
do
    singleEda "$filename"
done

echo "Have analyzed all data in this directory, please check the lcd file"
