#!/bin/bash

#********************************************************
# this code used to get LMOEDA compute data 
# LCD DIPOLES
# ........
# ........
# ...DONE WITH ENERGY LOCALIZATION...
# and output the data to filename.lcd
#********************************************************
#echo $1
if [ $# -eq 0 ]; then
    echo "eda [-r --report|-s --summary] <path>"
    exit 1
elif [ $# -eq 1 ]; then
    for filename in ./*eda*.out
    do
        singleEda $1 "$filename"
    done
elif [ $# -eq 2 ]; then
    if [[ $1 == '-r' || $1 == '--report' ]];then
        for filename in $2/*eda*.out
        do
            singleEda -r "$filename"
        done
    elif [[ $1 == '-s' || $1 == '--summary' ]];then
        for filename in $2/*eda*.out
        do
            singleEda -s "$filename"
        done
    else
        echo "eda -r --report|-s --summary <path>"
        exit 1
    fi
fi
