#!/bin/env python3
# -*- coding: UTF-8 -*-

"""
    This file combined with the script getEnergy which supply 
    the data that come from the Gamess output file(EDA).
"""

import sys

def Split(sdata, method='mp2'):
    """
        Split       split the origin data to fragment 
                    in order to handle
            sdata   the origin data that come from script getEnergy

    """
    # the data script supplied split with \n
    data = sdata.split('\n')
    if method == 'mp2':
    # fetch the data (MP2)
        ownData = [ float(i) for i in data[1:14:2] ]
        allData = [ float(i) for i in data[15:28:2] ]
    elif method == 'dft':
    # fetch the data (DFT)
        ownData = [ float(i) for i in data[1:12:2] ]
        allData = [ float(i) for i in data[13:24:2] ]
    else:
        print('the parameter is incorrect. Only choose dft/mp2.' )
        sys.exit(1)
    return (ownData, allData)

def Print(data, flag='ALL'):
    """
    Print       print a perfect struct data
        data    the data need output than contain two list
    """
    Es = "Es".center(10)
    Ex = "Ex".center(10)
    Rep = "Rep".center(8)
    Pol = "Pol".center(8)
    Disp = "Disp".center(10)
    E1 = "E(HF/DFT)".center(10)
    E2 = "E(MP2)".center(10)

    Es = "Es".center(10)
    Ex = "Ex".center(10)
    Rep = "Rep".center(8)
    Pol = "Pol".center(8)
    Disp = "Disp".center(10)
    E1 = "E(HF/DFT)".center(10)
    E2 = "E(MP2)".center(10)

    if flag == 'ALL':
        print ("-"*70)
        print("Own Basis Set EDA".center(70))
        print(Es, Ex, Rep, Pol, Disp, E1, E2)
        printData( data[0] )

        print("All Basis Set EDA".center(70))
        print(Es, Ex, Rep, Pol, Disp, E1, E2)
        printData( data[1] )
    elif flag == 'own':
    #   print("Own Basis Set EDA".center(70))
    #   print(Es, Ex, Rep, Pol, Disp, E1, E2)
        printData( data[0] )
    elif flag == 'all':
    #   print("All Basis Set EDA".center(70))
    #   print(Es, Ex, Rep, Pol, Disp, E1, E2)
        printData( data[1] )

def printData(data):
    """
    """
    for i in data:
        #print( str(i).center(10), end=';' )
        #output csv file   
        print( str(i), end=';' )
    print()


if __name__ == "__main__":
    if len(sys.argv) == 1:
        print("Input error!\nPlease enter an file name.")
        sys.exit(1)
    elif len(sys.argv) == 3:
        Print( Split(sys.argv[1], sys.argv[2] ) )
    elif len(sys.argv) == 4:
        Print( Split(sys.argv[1], sys.argv[2] ), sys.argv[3] )
    else:
        Print( Split(sys.argv[1]) )
    sys.exit(0)
