#!/bin/env python3

"""This script used to get LMOEDA energy E(polarization)

Now: Thu Apr 12 11:37:00 CST 2012
    analysis E(pol)

TODO:
    analysis every orbital E(pol)

"""

import sys
import os
from optparse import OptionParser

def ParseOption():
    """
    """
    usage = "Usage: %prog [options] filename"
    p = OptionParser(usage)
    p.add_option('-m', '--method', action='store', dest='method',
                    help="""Setup the quantum chemistry method you \
            used to EDA. [Default: %default]""", default='mp2')
    options, argv = p.parse_args()
    if not argv:
        print("")
    if options.method == 'mp2':
        i = 6
    elif options.method == 'dft':
        i = 7
    else:
        print("The method you choose is wrong")
        sys.exit(1)

    return (i, argv[0])


if __name__ == "__main__":

    hartree = 627.510
    oformat = "{:.8}"
    iType, filename = ParseOption()
    cmd = "tail -1000 %s | sed -n '/(REPULSION ENERGY: T V X J CHANGE)/, /SUMMARY OF INTERACTION ENERGIES/{p;}' |sed '/\(^$\)\|\(^ (\)\|\(^ -\)\|\(^ S\)\|\(^  \)/d;'" % filename
    items = []

    dpolarization = os.popen(cmd).readlines()

    for line in dpolarization:
        tvzjn = line.split()
        items.append(tvzjn[1:3])
    for i in range(iType):
        diff = (float(items[i + iType][1]) - float(items[i][1])) * hartree
        a = oformat.format(diff)
        print(str(a).rjust(15), end="")
    print()
