#!/bin/bash

#----------------
#
#---------------
if [ -z $1 ]; then
    echo "input error! Please type in file type which you want to process."
    exit 1
fi
if [ `echo $1 | grep 'eda'` ]; then
    echo "Extract Eda Data Successfully! "
    sed -n '/LCD DIPOLES/,/DONE WITH ENERGY LOCALIZATION/{/#/d;p;}' $1 > ${1%.*}.lcd
    if checkdata ${1%.*}.lcd ;then
        exit 0
    else
        exit 1
    fi
elif [ `echo $1 | grep 'opt'` ]; then
    echo "Extract Optimized Coordination Successfully!"
    sed -n '/LCD DIPOLES/,/DONE WITH ENERGY LOCALIZATION/{/#/d;p;}' $1 > ${1%.*}.cor
    if checkdata ${1%.*}.cor ;then
        exit 0
    else
        exit 1
    fi
fi
