#!/bin/bash

#set -x

TMPDIR="/state/partition1/$(whoami)"

#
#
# The main() function parser command-line option and perform operate.
#
#
main(){
    command=''
# ---------------- analysis command option --------------
    if [ $1 == 'list' ]||[ $1 == 'show' ];then
        if [ -z $2 ]||[ $2 == 'all' ];then
            Execute 'list'
        elif `echo "$2" | grep -q '^c01'`; then
            result=`ssh -Y $2 "ls $TMPDIR"`
            echo "On $2:"
            echo $result
            return 0
        else
            echo "input error!"
            echo "Usage: cmd <list|show|del> [all]"
            exit 1
        fi
    elif [ $1 == 'del' ];then
        if [ -z $2 ]||[ $2 == 'all' ];then
            echo "Delete Temp File On $2:"
            Execute "del"
            return 0
        elif `echo $2 | grep -q '^c01'`; then
            echo "Delete Temp File On $2:"
            Del $2
            return 0
        else
            echo "input error!"
            echo "Usage: cmd <list|show|del> [all]"
            exit 1
        fi
    else
        echo 'Input Error!'
        echo "Usage: cmd <list|show|del> [all]"
        exit 1
    fi
}

#
#
# Function Execute() choose the operation by the command 'list' or 'del'
# 'list'    will list the temp dir on the node
# 'del'     will del the temp file which isn't used on the node
#
#
Execute(){
    for i in `seq -f "%02g" 11`
    do
        if [[ "$1" == 'list' ]];then
            echo "On c01$i:"
            ssh -Y "c01$i" "ls $TMPDIR"
        elif [[ "$1" == 'del' ]];then
            Del "c01$i"
        fi
    done
}

#
#
# Function Del() check the file and delete it
#
#
Del(){
    for dir in $(ssh -Y "$1" "ls $TMPDIR")
    do
        echo $dir
        result=`ssh -Y "$1" "ls $TMPDIR/$dir | xargs -I {} lsof $TMPDIR/$dir/{} | egrep -c '[a-z]'"`
        echo $result
        if [[ $result -eq 0 ]];then
            ssh -Y "$1" "rm -rfv $TMPDIR/$dir"
        else
            echo "Some program is using the file."
            break
        fi
    done
}

#
#
# Current just accept two parameter
#
#
if [ -z $1 ];then
    main list
else
    main $1 $2
fi
