#!/bin/bash

if [ -z $1 ]; then
    echo "Input error! Please enter an file name."
    exit 1
fi

filename=$1
echo "--------------------------------$filename----------------------------"
if sedone $filename; then
    lcd_fileName="${filename%.*}.lcd"
    #echo chechdata $?
    #if checkdata "$lcd_fileName"; then
        if refine "$lcd_fileName"; then
            offset "${filename%.*}.tmp"
            getEnergy "$filename"
        else
            echo "Refine Data error!"
        fi
    #fi
fi
