#!/bin/bash

if [ -z $1 ]; then
    echo "Input error! Please enter an file name."
    echo "singleEda [-r --report|-s --summary] FileName"
    exit 1
fi

if [ $# -eq 1 ];then
    x=0
    filename=$1
elif [ $# -eq 2 ];then
    echo $1
    if [[ $1 == '-r' || $1 == '--report' ]];then
        x=1
    else
        x=0
    fi
    filename=$2
fi

echo "--------------------------------$filename----------------------------"
if sedone $filename; then
    lcd_fileName="${filename%.*}.lcd"
    if refine "$lcd_fileName"; then
        if [ $x -eq 0 ]; then
        # Output Summary
            offset -s "${filename%.*}.tmp"
            getEnergy "$filename"
        else
        # Output Result to file LCD and Energy
            offset -c "${filename%.*}.tmp">>LCD
            getEnergy "$filename">>Energy
        fi
    else
        echo "Refine Data error!"
    fi
fi
